# Generated by Django 5.1.7 on 2025-03-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipe_author_recipe_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('respective_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_recipe', to='ledger.recipe')),
            ],
        ),
    ]
