# Generated by Django 5.1.7 on 2025-03-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_recipeimage_respective_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='respective_recipe',
            new_name='recipe',
        ),
    ]
